### ISSUE TITLE
UserID Regenerated Every Time Reward Center is Opened

### ISSUE THREAD

**Issue by emmavray** [peanut-labs/publisher-ios-sdk#1]
PeanutLabsManager openRewardsCenter causes the userID to be regenerated.

If you're generating the userID server-side (recommended), then this regeneration will fail (application key not present).

Recommend you either check for presence of a userID before generating, or have a didGenerateUserIDRemotely boolean that disables local regeneration.

**Comment by saadullahsaeed** [comment]
Hey, thanks for reporting this. We were trying to support the use case of "switching user ids" and somehow the issue slipped in. About to push an update to check if the userId is pre-generated (not nil) and setting it to nil on the close event, that will take care of it.

Many thanks for pointing it out.

**Comment by saadullahsaeed** [comment]
Fixed in the latest commit:
https://github.com/peanut-labs/publisher-ios-sdk/commit/a0370c7f57d2cbdae20d4e5d92c817c14c6e9d7e
