### ISSUE TITLE
Special characters in the userId, break the code.

### ISSUE THREAD

**Issue by JimJty** [peanut-labs/publisher-ios-sdk#2]
If I use special characters in the userId, the offerwall does not load. 

For example, if I use the pipe character to separate portions of my userId:

``` ios
[plManager setEndUserId:@"1234|100"];
```

The fix would be to percent encode the userId. I assume all the user defined fields need this fix.

**Comment by saadullahsaeed** [comment]
Thanks for reporting this. All the variables should indeed be URL encoded. We will commit the fix for this shortly.

**Comment by Bilguun39** [comment]
Thanks for reporting, fix is committed, please let me know if you see any other issues
